name: CMake

on: [push, pull_request]

env:
  BUILD_TYPE: RelWithDebInfo

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y g++
          sudo apt install -y cmake

      - name: Build and install OpenCV 4.5.1
        run: sudo bash .github/scripts/install_opencv451.sh;

      - name: Install Eigen 3
        run: sudo bash .github/scripts/install_eigen3.sh

#      - name: Install OpenCL CPU driver
#        run: sudo bash .github/scripts/install_intel_opencl.sh;

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: test_sift
        working-directory: ${{github.workspace}}
        run: ./build/test_sift

      - name: test_matching
        working-directory: ${{github.workspace}}
        run: ./build/test_matching
